name: flutter_oauth2_login
description: A new Flutter project.
publish_to: 'none' # since it's not a package to be published
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  http_interceptor: ^1.0.1
  email_validator: ^2.1.17
  flutter_easyloading: ^3.0.5
  intl: ^0.19.0

flutter:
# fonts:
#   - family: Roboto
#     fonts:
#       - asset: fonts/Roboto-Regular.ttf
#       - asset: fonts/Roboto-Bold.ttf
#       - asset: fonts/Roboto-Italic.ttf
